### ISSUE TITLE
Allow remote sensing featurizer to process data in batches

### ISSUE THREAD

**Issue by cdbethune** [kungfuai/d3m-primitives#15]
Currently the remote sensing featurizer is running out of RAM when dealing with larger datasets.  It seem that the issue is due to the fact that featurizer is loading all of the remote sensing data from the input dataframe into a `TensorDataset`, then passing that data into the data loader:

```python
        image_dataset = self._load_dataset(inputs, image_col)
        image_dataset = TensorDataset(image_dataset)
        image_loader = DataLoader(
            image_dataset,
            batch_size=self.hyperparams['batch_size'],
        )
```

It looks like Pytorch supports the idea of an iterable dataset (, which should allow for us to load the images from the dataframe one at a time (or in batches) for featurization.  This may be a good starting point:  https://medium.com/speechmatics/how-to-build-a-streaming-dataloader-with-pytorch-a66dd891d9dd

We can also clear out the RAM associated with the raw images as we go to reduce memory pressure further.

**Comment by cdbethune** [comment]
Noticed in testing that the original features for the dataset are being dropped.  So, if we have a dataframe consisting of:

`[d3m_index, tile_id, geo_coords, timestamp, image_data]`

we get back:

`[feature_0, feature_1, ..., feature_n]`

We were hoping to get:

`[d3m_index, tile_id, geo_coords, timestamp, feature_0, feature_1...feature_n]`.

We can adjust the pipeline to include a horizontal concat step, but it would be better if we could just append.

**Comment by jlgleason** [comment]
Addressed in latest MR!
